a = input()
b = input()
original_c = str(int(a)+int(b))
new_a = "".join([i for i in a if i != "0"])
new_b = "".join([i for i in b if i != "0"])
new_c = "".join([i for i in original_c if i != "0"])
print("YES" if int(new_a) + int(new_b) == int(new_c) else "NO")
